### ISSUE TITLE
[doc] Issue in "Upgrade to latest version"

### ISSUE THREAD

**Issue by wombelix** [SUSE/technical-reference-documentation#75]
Upgrade to latest version:

https://documentation.suse.com/trd/kubernetes/single-html/gs_rancher_aws-marketplace/#id-upgrade-to-latest-version

It should be mentioned in this Section that the Helm deployment name is `rancher-stable` if Rancher Setup was used. The linked Rancher guide assumes that it's named `rancher`, which will lead to a situation that the commands fail and the customer has to dig deeper to figure out the right name.

**Comment by wombelix** [comment]
OK after getting feedback from @kevinayres it seems like my request caused confusion.
I'm referring to the `Helm Deployment` name _not_ the `Helm Repository`.

The above mentioned installation guide basically just refers to https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades#3-upgrade-rancher and this guide uses `rancher` as Helm Deployment name in all examples.

From the Guide, with `rancher` as deployment name:
```
helm get values rancher -n cattle-system -o yaml > values.yaml

helm upgrade rancher rancher-<CHART_REPO>/rancher \
--namespace cattle-system \
-f values.yaml \
--version=2.6.8
```

How it must look like, with `rancher-stable` as Helm deployment name, to work if Rancher Setup was used to make the initial deployment:
```
helm get values rancher-stable -n cattle-system -o yaml > values.yaml

helm upgrade rancher-stable rancher-<CHART_REPO>/rancher \
--namespace cattle-system \
-f values.yaml \
--version=2.6.8
```

I don't think it's much valuable to add it to the Rancher Upgrade Guide, that's why I suggested to mention the different Helm Deployment name in Section 4 of https://documentation.suse.com/trd/kubernetes/single-html/gs_rancher_aws-marketplace/#id-upgrade-to-latest-version to make people aware about it. Otherwise they will most likely see error messages that the Helm deployment `rancher` couldn't be found and then have to figure out on their own that the name is actually `rancher-stable`.

**Comment by chabowski** [comment]
@kevinayres @tlssuse We have an open issue for this document - would you mind having a look? Thank you!

**Comment by kevinayres** [comment]
updated in PR: https://github.com/rancher/rancher-docs/pull/747

**Comment by tlssuse** [comment]
Thank you, @kevinayres.  Do you think we should also add a note to the getting started guide about the naming difference?

**Comment by chabowski** [comment]
@kevinayres @tlssuse please let me know when/if we can close the issue. Thank you!

**Comment by tlssuse** [comment]
@kevinayres : I know this may need to be updated again after the new marketplace listing is published, but we could add an admonition around line 401.  Something like the following might work:

`

[IMPORTANT]
====
When using the {offering1} marketplace listing, the deployment name is `rancher-stable` instead of `rancher`.

Thus, to export the Helm chart values of your current {product1} deployment, you would use:
[source, console]
----
helm get values rancher-stable -n cattle-system -o yaml > values.yaml
----

And to upgrade to a specific <RANCHER-VERSION>, you would use:
[source, console]
----
helm upgrade rancher-stable rancher-<CHART_REPO>/rancher \
  --namespace cattle-system \
  -f values.yaml \
  --version=<RANCHER-VERSION>
----

====
`

What do you think?
